name: Nuget-Publish

on:
  push:
    branches:
      - main
      
jobs:
  publish:
    name: pack + publish
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Create the package
      run: dotnet pack --configuration Release ./src/working/deverqqqq.Templates.csproj
      
    - name: Publish the package to nuget.org
      run: dotnet nuget push ./src/working/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGETSERVERAPI }}
